version: '2'
services:
    sc-app:
        image: sc
        external_links:
            - sc-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/sc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sc-postgresql:
        extends:
            file: postgresql.yml
            service: sc-postgresql
